services:
  db:
    image: postgres:16-alpine
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: bicak
    ports:
      - "5432:5432"
    volumes:
      - bicak_pg_data:/var/lib/postgresql/data

volumes:
  bicak_pg_data:
